// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQHTZiIt-f2smr7OD-z3hY1u9-8XqKVe0',
    appId: '1:978907177516:web:caf3772577b67371efa789',
    messagingSenderId: '978907177516',
    projectId: 'brew-crew-5ee31',
    authDomain: 'brew-crew-5ee31.firebaseapp.com',
    storageBucket: 'brew-crew-5ee31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEQTZZjqvBpOLRy3fMKEqroBLUGxXKrjM',
    appId: '1:978907177516:android:ad30f937306d4d5fefa789',
    messagingSenderId: '978907177516',
    projectId: 'brew-crew-5ee31',
    storageBucket: 'brew-crew-5ee31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDosMURAt034DumEqeKvRDRbUnNJlaXuyI',
    appId: '1:978907177516:ios:9202eb15945294cdefa789',
    messagingSenderId: '978907177516',
    projectId: 'brew-crew-5ee31',
    storageBucket: 'brew-crew-5ee31.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDosMURAt034DumEqeKvRDRbUnNJlaXuyI',
    appId: '1:978907177516:ios:a4c737ce72400ba5efa789',
    messagingSenderId: '978907177516',
    projectId: 'brew-crew-5ee31',
    storageBucket: 'brew-crew-5ee31.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
